import{a as w,S as v,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const q="51401862-5106c302b458f745abd86383c",S="https://pixabay.com/api/";async function d(n,o){const e={key:q,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await w.get(S,{params:e})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".btn"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(n){const o=n.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><span class="span-info">Likes<br></span>${e.likes}</p>
            <p><span class="span-info">Views<br></span>${e.views}</p>
            <p><span class="span-info">Comments<br></span>${e.comments}</p>
            <p><span class="span-info">Downloads<br></span>${e.downloads}</p>
          </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",o),R.refresh()}function C(){p.innerHTML=""}function g(){f.classList.remove("is-hidden")}function m(){f.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const L=document.querySelector(".form"),M=L.elements["search-text"],P=document.querySelector(".btn");let s=1,u="";L.addEventListener("submit",async function(n){n.preventDefault();const o=M.value.trim();if(!o){a.warning({message:"Please enter a search query!",position:"topRight"});return}u=o,s=1,C(),l(),g();try{const e=await d(u,s);e.hits.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ff4c4c",position:"topRight"}):(y(e.hits),e.totalHits>s*20&&b())}catch{a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{m()}});P.addEventListener("click",async function(){s+=1,g(),l();try{const n=await d(u,s);y(n.hits);const o=Math.ceil(n.totalHits/20);s>=o?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):b();const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch{a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
